version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
        - echo Logging in to Amazon ECR...
        - aws --version
        - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
        - echo Show folder content
        - ls -la
        - echo Maven version
        - mvn -version
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - docker build -t fabricaregional.dkr.ecr.us-east-2.amazonaws.com/coopeuch-demo:latest .
  post_build:
    commands:
        - echo Pushing Docker image to ECR...
        - docker push fabricaregional.dkr.ecr.us-east-2.amazonaws.com/coopeuch-demo:latest
        - echo Updating Kubernetes deployment...
        - kubectl apply -f k8s