version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
        - echo Logging in to Amazon ECR...
        - aws --version
        - echo Show folder content
        - ls -la
        - echo Maven version
        - mvn -version 
        - export KUBECONFIG=$HOME/.kube/config
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - docker build -t 846869029012.dkr.ecr.us-east-2.amazonaws.com/coopeuch:latest .
      - echo Show docker image
      - docker images
  post_build:
    commands:
        - echo Pushing Docker image to ECR...
        - docker push 846869029012.dkr.ecr.us-east-2.amazonaws.com/coopeuch:latest
        - echo Set EKS
        - aws eks --region us-east-2  update-kubeconfig --name eks-coopeuch-demo01
        - echo GET Nodes
        - kubectl get nodes 
        - echo Updating Kubernetes deployment...
        - kubectl apply -f k8s