version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
        - echo Logging in to Amazon ECR...
        - aws --version
        - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 	846869029012.dkr.ecr.us-east-2.amazonaws.com/coopeuch
        - REPOSITORY_URI=846869029012.dkr.ecr.us-east-2.amazonaws.com/coopeuch
        - echo Show folder content
        - ls -la
        - echo Maven version
        - mvn -version 
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - docker build -t 846869029012.dkr.ecr.us-east-2.amazonaws.com/coopeuch:latest .
      - echo Show docker image
      - docker images
  post_build:
    commands:
        - echo Pushing Docker image to ECR...
        - docker push 846869029012.dkr.ecr.us-east-2.amazonaws.com/coopeuch:latest
        - echo Set EKS
        - aws eks update-kubeconfig --region us-east-2 --name eks-coopeuch-demo --role-arn arn:aws:iam::846869029012:policy/service-role/CodeBuildBasePolicy-coopeuch-demo-build-us-east-2
        - echo Updating Kubernetes deployment...
        - kubectl apply -f k8s 