version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
        - echo Logging in to Amazon ECR...
        - aws --version
        # - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 	846869029012.dkr.ecr.us-east-2.amazonaws.com/coopeuch
        - docker login --username docker-user --password $DOCKER_PASSWORD https://nexus-test-cp4i.apps.66fb28d07658ddb185cbb03c.ocp.techzone.ibm.com
        - echo Show folder content
        - ls -la
        - echo Maven version
        - mvn -version 
        - export KUBECONFIG=$HOME/.kube/config
        - echo create .m2
        - mkdir -p ~/.m2
        - echo set maven settings
        - cp settings.xml ~/.m2/settings.xml
        - cat ~/.m2/settings.xml
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - echo Deploying to Nexus
      - mvn:deploy
      - docker build -t nexus-test-cp4i.apps.66fb28d07658ddb185cbb03c.ocp.techzone.ibm.com/coopeuch:latest .
      - echo Show docker image
      - docker images
  post_build:
    commands:
        - echo Pushing Docker image to ECR...
        - docker push nexus-test-cp4i.apps.66fb28d07658ddb185cbb03c.ocp.techzone.ibm.com/coopeuch:latest
        # - echo Set EKS 
        # - aws eks update-kubeconfig --region us-east-2 --name eks-coopeuch-demo01
        # - cat /root/.kube/config
        # - echo GET Nodes
        # - kubectl get nodes 
        # - echo Updating Kubernetes deployment...
        # - kubectl apply -f k8s 